# Generated by Django 4.2.30 on 2026-04-23 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('finished', 'Finished')], default='planned', max_length=10)),
                ('first_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_as_first', to='cats.cat')),
                ('second_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_as_second', to='cats.cat')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat')),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='duels.duel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'duel'), name='unique_vote_per_user'),
        ),
    ]
