# Generated by Django 4.2.30 on 2026-05-08 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cat_image'),
        ('duels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duel',
            name='is_draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duel',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duel',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_duels', to='cats.cat'),
        ),
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duel',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CatStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='cats.cat')),
            ],
        ),
    ]
