# Generated by Django 4.2.30 on 2026-05-08 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cat_image'),
        ('duels', '0002_duel_created_at_duel_is_draw_duel_is_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='catstats',
            name='total_duels',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to='cats.cat')),
            ],
        ),
        migrations.AddField(
            model_name='duel',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duels', to='duels.tournament'),
        ),
    ]
