# Generated by Django 4.2.30 on 2026-05-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0003_remove_duel_is_processed_catstats_total_duels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duel',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
