# Generated by Django 4.2.30 on 2026-05-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0004_alter_duel_end_time_alter_duel_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
