# Generated by Django 4.2.30 on 2026-05-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='cats/images/'),
        ),
    ]
